runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /ng
  static_dir: ng

- url: /(index\.html)
  static_files: static/\1
  upload: static/(.*)

- url: /(robots\.txt|favicon\.ico|sitemap\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: server.app