runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(robots\.txt|favicon\.ico|sitemap\.txt|index\.html|*\.css)
  static_files: static/\1
  upload: static/(.*)

- url: /app
  static_dir: app

- url: /.*
  script: server.app
